### ISSUE TITLE
Output in json format

### ISSUE THREAD

**Issue by piranna** [alexfernandez/performance#1]
Add flag to allow write output as a JSON object, or also write it to a file in that format. This would allow automatic analisis later.

**Comment by alexfernandez** [comment]
It's an excellent idea. Do you think you might tackle it?

**Comment by piranna** [comment]
I'm a little bit time constrained, but I'll try to do it. If you want to take it a look yourself please tell me.

**Comment by alexfernandez** [comment]
OK, it was easy to do, you have it in version 1.0.0. Just run:

```
node bin/performance.js --json
```

and it should do the trick. Also, you can use programmatically, as you can see in the README.

**Comment by piranna** [comment]
Wow, thank you so much, it was quick! :-D I'm going to try it now :-)

**Comment by piranna** [comment]
Checked and working like a charm, fairly better than copying the data by hand ;-) Thanks! :-D

**Comment by alexfernandez** [comment]
Any time! :)
